### ISSUE TITLE
Docker links and install broken

### ISSUE THREAD

**Issue by shageman** [cloudfoundry-samples/lattice-app#5]
Please excuse if this is the wrong place, but the link from http://lattice.cf/docs/getting-started/ to the docker page for lattice-app is broken. It should be https://registry.hub.docker.com/u/cloudfoundry/lattice-app/

Also, for me `docker pull cloudfoundry/lattice-app` has stopped working.

**Comment by davidwadden** [comment]
We've submitted an update to the team that maintains the lattice.cf website to fix the broken link.

As far as problems with `docker pull`, are you still experiencing these ? We just did an install of docker to a fresh linux box, and had no problems, and we haven't received any other reports lately.

**Comment by shageman** [comment]
Thanks

I believe those docker issues were homemade...
